// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("GreenPipes")]
[assembly: AssemblyDescriptionAttribute("GreenPipes, a pipes and filters framework for the Task Parallel Library")]
[assembly: AssemblyProductAttribute("GreenPipes")]
[assembly: AssemblyVersionAttribute("1.0.0.0")]
[assembly: AssemblyFileVersionAttribute("1.0.4.0")]
[assembly: AssemblyInformationalVersionAttribute("1.0.4.0 (p1/91d5b6dc)")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "GreenPipes";
        internal const System.String AssemblyDescription = "GreenPipes, a pipes and filters framework for the Task Parallel Library";
        internal const System.String AssemblyProduct = "GreenPipes";
        internal const System.String AssemblyVersion = "1.0.0.0";
        internal const System.String AssemblyFileVersion = "1.0.4.0";
        internal const System.String AssemblyInformationalVersion = "1.0.4.0 (p1/91d5b6dc)";
    }
}
